### ISSUE TITLE
No Plugins in my Kap

### ISSUE THREAD

**Issue by yimmy23** [wulkano/kap#820]
**macOS version:**    10.15.4
**Kap version:**      3.2.0

#### Current behavior
Kap plugins are empty
![image](https://user-images.githubusercontent.com/45797848/78639486-a08faf80-78e0-11ea-8ddc-21580e9ba280.png)
#### Expected behavior
How can i fix it，thanks for your help.

**Comment by yimmy23** [comment]
![image](https://user-images.githubusercontent.com/45797848/78639725-07ad6400-78e1-11ea-8e72-eba31dc567ac.png)
After a 20 minutes, It suggests Something went wrong…

**Comment by karaggeorge** [comment]
Usually that means the call to fetch the plugins was unsuccessful. So that means you either didn't have internet connection or the service we use for the plugins might have been down.

Can you ensure you have internet connection and try one more time? I just checked and the service seems to be up and running. I'll keep this issue open until we can make sure it's fixed

**Comment by karaggeorge** [comment]
We are also actively working on a better indicator for what's happening on that page (fetching/loading/error), so it's a bit more user friendly

**Comment by yimmy23** [comment]
Thanks for your reply!
I think my Internet connection is fine.
How can I know if my internet connection in Kap is ok ? I have use proxy and I can watch youtube or google. I can use proxy to download Kap plugins or manually install plugins?

**Comment by yimmy23** [comment]
I have tried to reinstalled v3.2.0 and install v3.1.0, 
In version 3.1.0, it looks like 
![image](https://user-images.githubusercontent.com/45797848/78687341-a4462500-7926-11ea-8066-ca1af1d2e50e.png)

**Comment by karaggeorge** [comment]
@yimmy23 

Would you mind exiting the app, erasing the following directory and trying again: `~/Library/Application\ Support/Kap/plugins`

**Comment by yimmy23** [comment]
Thanks for your advice. I installed v3.0.1 first and  then v3.2.0, and the problem was solved. Thanks for your advice.

**Comment by cipri-tom** [comment]
@karaggeorge I have the same problem as OP, with Kap version 3.3.2.1718 .

Some websites are blocked by my employer, but usually using a VPN gives access. However, with Kap it still doesn't work. Can you share where the plugins are hosted, or if I can somehow install them by hand ? Or maybe give more details about the issue.

The Refresh link also does nothing, doesn't look like it can be clicked. I tried re-installing, and removing the `plugins` folder, to no avail :(
