### ISSUE TITLE
Videos not being saved

### ISSUE THREAD

**Issue by tiagorocha1979** [wulkano/Kap#911]
Hi,

When I try to save my capture as video, it doesn't save it. It shows an error. For example:
ffmpeg exited with code: 1 ffmpeg version N-92718-etc, etc, etc....

I can export as a GIF, though.

macOS version:       macosx 10.13.6
Kap version:          3.2.2

**Comment by karaggeorge** [comment]
Do you happen to have the full error code? Also the issue might be already fixed just not released, so we'll monitor this after we release our next version.

Related #849 

See this comment/discussion: https://github.com/wulkano/Kap/issues/849#issuecomment-663116736

**Comment by steveharman** [comment]
I'm getting this too.  Saving is fine for GIF but on MP4 it fails.

The error is truncated in the Kap window - where can I go to extract the full message please @karaggeorge ?  I had a hunt around in Console without success

- macOS 10.15.6
- Kap 3.2.2 (3.2.2.1577)

Thanks,

Steve

![kapError](https://user-images.githubusercontent.com/12557929/90639062-12302080-e226-11ea-848c-95c11515b9a2.png)

**Comment by karaggeorge** [comment]
This was an issue with odd dimensions. It has been fixed in the latest release 3.3.0

**Comment by tiagorocha1979** [comment]
I just downloaded the new version, same issue. It's not solved yet.
Also, it took more than usual to open the app and record anything.

**Comment by noahduran1** [comment]
How long does an export take? I'm trying to export a recording(30 mins long) but it says 2 days approx time. I'm in V3.3.1 and version 10.14.6 mac.

**Comment by karaggeorge** [comment]
What kind of options are you using? Format/size/fps?
